name: Automatic releases

on:
  workflow_dispatch:
  schedule:
    - cron: '5 4 * */5 0'

jobs:
  auto-release:
    runs-on: ubuntu-latest
    steps:
      - name: Releasing if there is something new...
        uses: impresscms-dev/simple-autorelease-action@v0.2
        with:
          release_branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: patch
